# Developed https://t.me/IBoTuS

settings:
  messages: "#0EC8E2[✘] &fВы не можете #0EC8E2поместить &fэтот предмет в Эндер-Скриню!"
  sound:
    name: ENTITY_ITEM_PICKUP # Название
    volume: 1.0 # Громкость
    pitch: 1.0 # Темп
  items-ban-list: # Список запрещенных предметов
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - RED_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - PINK_SHULKER_BOX